### ISSUE TITLE
how to change the language of the extension to english

### ISSUE THREAD

**Issue by GitAutopoc** [breaking-point/vsce-postman#3]

**Comment by GitAutopoc** [comment]
![image](https://user-images.githubusercontent.com/98872904/207774019-54f9f7f7-4451-4aa8-af12-40af9fdab9ac.png)

**Comment by DevXiaolan** [comment]
`study Chinese maybe good for you`

**Comment by bingcoder** [comment]
Thank you for use, please use official Postman Extension
感谢使用，现在可以使用 postman 官方的扩展了 https://marketplace.visualstudio.com/items?itemName=Postman.postman-for-vscode
