### ISSUE TITLE
Rate limit exceeded exception from Octokit

### ISSUE THREAD

**Issue by GitAutopoc** [breaking-point/vsce-postman#4]
I'm trying to create 150 repositories in Git at the same time using the Octokit Rest API.
While doing so, i'm receiving rate limit exceeded exception from the Octokit API.
The rate limit provided is 5000/per hour and I also checked my rate limit at that point and it showed 4800+ calls remaining.

What could be the potential cause for this scenario, is it with the Octokit API (or) do we have any rate limiting per minutes/seconds?
Kindly assist me to narrow down this issue.

**Comment by bingcoder** [comment]
I'm sorry, I can't help you.
